# Generated by Django 4.2.5 on 2024-09-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0002_house_pets_allowed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="pets_allowed",
            field=models.BooleanField(
                default=True, help_text="Is pet allowed?", verbose_name="Pets allowed?"
            ),
        ),
    ]
