# Generated by Django 4.2.5 on 2024-09-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perk",
            name="detail",
        ),
        migrations.AddField(
            model_name="perk",
            name="details",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
