"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from environs import Env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


env = Env()
env.read_env()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

AUTH_USER_MODEL = 'users.User'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'rooms.apps.RoomsConfig',
    'common.apps.CommonConfig',
    'experiences.apps.ExperiencesConfig',
    'categories.apps.CategoriesConfig',
    'reviews.apps.ReviewsConfig',
    'wishlists.apps.WishlistsConfig',
    'bookings.apps.BookingsConfig',
    'medias.apps.MediasConfig',
    'direct_messages.apps.DirectMessagesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USERNAME'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = 'uploads'

MEDIA_URL = 'user-uploads/'


# 파일 스토리지
# 어느 백엔드로 업로드할지 고른다. common/storage/__init__.py 가 이 값으로 분기한다.
UPLOAD_SERVER = env('UPLOAD_SERVER', 'UPLOADTHING').upper()

UPLOAD_SERVER_CHOICES = ('UPLOADTHING', 'AWS')
if UPLOAD_SERVER not in UPLOAD_SERVER_CHOICES:
    # 런타임에 502로 터지기 전에 부팅 시점에 잡는다
    raise ImproperlyConfigured(f'UPLOAD_SERVER는 {UPLOAD_SERVER_CHOICES} 중 하나여야 합니다. 현재 값: {UPLOAD_SERVER!r}')

# 업로드 허용 최대 크기 (bytes) — 백엔드와 무관하게 적용
UPLOAD_MAX_FILE_SIZE = env.int('UPLOAD_MAX_FILE_SIZE', 5 * 1024 * 1024)


# UPLOAD_SERVER=UPLOADTHING 일 때
# https://docs.uploadthing.com/api-reference/openapi-spec
#
# v7부터 UPLOADTHING_SECRET이 UPLOADTHING_TOKEN으로 통합됐다.
# 토큰은 apiKey/appId/regions를 담은 base64 JSON이며, REST 호출에는 그 안의 apiKey만 필요하다.
# 대시보드 > API Keys > V7 탭에서 발급.
UPLOADTHING_TOKEN = env('UPLOADTHING_TOKEN', '')


# UPLOAD_SERVER=AWS 일 때
# 자격증명을 비워두면 boto3가 환경변수/IAM 역할 등 기본 체인을 따라간다.
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME', '')
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME', '')

# DB에 영구 공개 URL을 저장하므로 버킷이 공개 읽기를 허용해야 한다.
# 2023년 4월 이후 만든 버킷은 ACL이 기본 비활성이라 아래를 비워두고 버킷 정책으로 여는 것이 정석이다.
# ACL이 활성화된 버킷이라면 'public-read'를 넣는다.
AWS_S3_ACL = env('AWS_S3_ACL', '')

# CloudFront 등을 앞에 뒀다면 그 도메인으로 URL을 만든다 (예: dxxxx.cloudfront.net)
AWS_S3_CUSTOM_DOMAIN = env('AWS_S3_CUSTOM_DOMAIN', '')
