# Generated by Django 4.2.28 on 2026-03-01 03:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('direct_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattingroom',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='chatting_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
